sudo: required
dist: xenial    # I wish this worked; defaults to trusty
services:
  - docker
before_install:
  - docker rm fboss_build fboss_build_phase2 fboss_build_phase3 || true   # clean up from any old runs
  # split docker commands up to avoid travis timeouts
  #    Between each phase, use 'docker commit' to make sure the subsequent
  #    phase starts off where the last one stopped
  #    
  # Phase 1 - build just the dependencies
  - docker run --name fboss_build -v `pwd`:/tmp/code opennetworklinux/builder9:1.0 /bin/sh -c "g++ --version ; cd /tmp/code && bash getdeps.sh"
  - docker commit fboss_build fboss/tmp  
script:
  # Phase 2 - build just libfboss_agent.a (most of the fboss code)
  - docker run --name fboss_build_phase2 -v `pwd`:/tmp/code fboss/tmp /bin/sh -c "cd /tmp/code && mkdir build && cd build && cmake .. && make -j`grep -c processor /proc/cpuinfo` fboss_agent"
  - docker commit fboss_build_phase2 fboss/tmp2
  # Phase 3 - build everything else
  - docker run --name fboss_build_phase3 -v `pwd`:/tmp/code fboss/tmp /bin/sh -c "cd /tmp/code && mkdir build && cd build && cmake .. && make -j`grep -c processor /proc/cpuinfo`"
  - docker commit fboss_build_phase3 fboss/tmp3
  # This hangs in travis !?!?  Need to debug
  # - docker run --name fboss_build_phase4 -v `pwd`:/tmp/code fboss/tmp /bin/sh -c "cd /tmp/code/build && make test"

notifications:
  email:
    - rsher@fb.com
  webhooks: https://code.facebook.com/travis/webhook
